//
// Created by chenhui on 2021/12/13.
//

#ifndef INSKY_INSPECTION_SUPPORTSYSTEMTYPES_HPP
#define INSKY_INSPECTION_SUPPORTSYSTEMTYPES_HPP

enum SystemTypes : uint8_t
{
    DJI_OSDK_BASED,
    MAVLINK_BASED,
    NO_SYSTEM
};

#endif //INSKY_INSPECTION_SUPPORTSYSTEMTYPES_HPP
